name: GHClient
configs:
  Debug: debug
  Release: release
options:
  groupSortPosition: top
attributes:
  ORGANIZATIONNAME: ymgn
fileGroups:
  - GHClient
settingGroups:
  app:
    DEVELOPMENT_TEAM: 7F6B255837
targets:
  GHClient:
    type: application
    platform: iOS
    sources:
      - path: GHClient
    attributes:
      SystemCapabilities:
        com.apple.BackgroundModes:
          enabled: 1
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ymgn.GHClient
        ASSETCATALOG_COMPIER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: GHClient/Info.plist
      configs:
        Debug:
          GCC_OPTIMIZATION_LEVEL: O
        Release:
          GCC_OPTIMIZATION_LEVEL: s
    dependencies:
      - carthage: SVProgressHUD
      - carthage: APIKit
      - carthage: RxSwift
      - carthage: Action
      - carthage: Kingfisher
  GHClientTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: GHClient
    settings:
      TEST_HOSTS: $(BUILT_PRODUCTS_DIR)/GHClient.app/GHClient
      INFORPLSIT_FILE: GHClientTests/Info.plist
    sources:
      - GHClientTests

schemes:
  GHClient:
    build:
      targets:
        GHClient: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

